// <auto-generated />
namespace WebBellwether.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class zarazciewypierdole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zarazciewypierdole));
        
        string IMigrationMetadata.Id
        {
            get { return "201511232227246_zaraz cie wypierdole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
