// <auto-generated />
namespace WebBellwether.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class jokev10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jokev10));
        
        string IMigrationMetadata.Id
        {
            get { return "201510192048377_joke v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
