// <auto-generated />
namespace WebBellwether.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class gfv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gfv2));
        
        string IMigrationMetadata.Id
        {
            get { return "201601142249133_gfv2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
